# Generated by Django 6.0.7 on 2026-07-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowdeskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
    ]
